spring:
  profiles: prod
---
spring:
  profiles: dev

---
otka:
  oauth2:
    client-id: 0oap5pp8tQpO9VgqS356
    issuer:  https://dev-210965.okta.com/oauth2/default
action-executor:
  thread-core-size: 1
  thread-max-pool-size: 1
  thread-queue-capacity: 1000
  max-failures: 3
logging:
  level:
    org:
      springframework:
        data:
          mongodb: OFF
    com:
      adrian:
        mobsters: TRACE
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}