spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://adrian:haxuk23D@localhost:27017/admin
    com:
      adrian:
        mobsters: TRACE
---
action-executor:
  thread-core-size: 1
  thread-max-pool-size: 1
  thread-queue-capacity: 1000
  max-failures: 3
springbootwebfluxjjwt:
  jjwt:
    expiration: 28800
  password:
    encoder:
      iteration: 33
      keylength: 256
logging:
  level:
    org:
      springframework:
        data:
          mongodb: OFF