spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://adrian:haxuk23D@localhost:27017/admin
logging:
  level:
    org: OFF
    com:
      adrian:
        mobsters: TRACE
---
action-executor:
  thread-core-size: 5
  thread-queue-capacity: 1000
  max-failures: 3