spring.application.name: mobster

---

spring:
  profiles: prod
spring.application.name: mobster
spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}

---

spring:
  profiles: dev
spring.data.mongodb.host: localhost
spring.data.mongodb.port: 27017
spring.application.name: mobster
spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/mobsters