spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_URI}
    com:
      adrian:
        mobsters: TRACE
---
action-executor:
  thread-core-size: 1
  thread-max-pool-size: 1
  thread-queue-capacity: 1000
  max-failures: 3
logging:
  level:
    org:
      springframework:
        data:
          mongodb: OFF
    com:
      adrian:
        mobsters: TRACE